<?php
return array (
  3 => 
  array (
    'id' => '3',
    'catid' => '13',
    'typeid' => '0',
    'title' => '企业新闻2',
    'style' => '',
    'thumb' => '',
    'keywords' => '企业 新闻',
    'description' => '企业新闻2企业新闻2企业新闻2企业新闻2企业新闻2企业新闻2企业新闻2企业新闻2企业新闻2企业新闻2企业新闻2企业新闻2企业新闻2企业新闻2企业   ',
    'posids' => '0',
    'url' => 'http://www.g-sky.cn/index.php?m=content&c=index&a=show&catid=13&id=3',
    'listorder' => '0',
    'status' => '99',
    'sysadd' => '1',
    'islink' => '0',
    'username' => 'admin',
    'inputtime' => '1422090859',
    'updatetime' => '1422165457',
    'hitsid' => 'c-1-3',
    'views' => '18',
    'yesterdayviews' => '17',
    'dayviews' => '1',
    'weekviews' => '18',
    'monthviews' => '18',
  ),
  1 => 
  array (
    'id' => '1',
    'catid' => '13',
    'typeid' => '0',
    'title' => '我是新闻1',
    'style' => '',
    'thumb' => '',
    'keywords' => '新闻',
    'description' => '我是新闻1我是新闻1我是新闻1我是新闻1我是新闻1我是新闻1我是新闻1我是新闻1我是新闻1我是新闻1我是新闻1我是新闻1我是新闻1我是新闻1我是   ',
    'posids' => '0',
    'url' => 'http://www.g-sky.cn/index.php?m=content&c=index&a=show&catid=13&id=1',
    'listorder' => '0',
    'status' => '99',
    'sysadd' => '1',
    'islink' => '0',
    'username' => 'admin',
    'inputtime' => '1422089890',
    'updatetime' => '1422095975',
    'hitsid' => 'c-1-1',
    'views' => '16',
    'yesterdayviews' => '0',
    'dayviews' => '16',
    'weekviews' => '16',
    'monthviews' => '16',
  ),
  5 => 
  array (
    'id' => '5',
    'catid' => '13',
    'typeid' => '0',
    'title' => '111111',
    'style' => '',
    'thumb' => '',
    'keywords' => '111111',
    'description' => '111',
    'posids' => '0',
    'url' => 'http://www.g-sky.cn/index.php?m=content&c=index&a=show&catid=13&id=5',
    'listorder' => '0',
    'status' => '99',
    'sysadd' => '1',
    'islink' => '0',
    'username' => 'admin',
    'inputtime' => '1422168113',
    'updatetime' => '1422168770',
    'hitsid' => 'c-1-5',
    'views' => '1',
    'yesterdayviews' => '0',
    'dayviews' => '1',
    'weekviews' => '1',
    'monthviews' => '1',
  ),
  6 => 
  array (
    'id' => '6',
    'catid' => '13',
    'typeid' => '0',
    'title' => '22222222222222222',
    'style' => '',
    'thumb' => '',
    'keywords' => '22222222222222222',
    'description' => '2222222222222222222',
    'posids' => '0',
    'url' => 'http://www.g-sky.cn/index.php?m=content&c=index&a=show&catid=13&id=6',
    'listorder' => '0',
    'status' => '99',
    'sysadd' => '1',
    'islink' => '0',
    'username' => 'admin',
    'inputtime' => '1422168334',
    'updatetime' => '1422168765',
    'hitsid' => 'c-1-6',
    'views' => '1',
    'yesterdayviews' => '0',
    'dayviews' => '1',
    'weekviews' => '1',
    'monthviews' => '1',
  ),
  4 => 
  array (
    'id' => '4',
    'catid' => '13',
    'typeid' => '0',
    'title' => '我是新闻三',
    'style' => '',
    'thumb' => '',
    'keywords' => '新闻',
    'description' => '我是新闻三我是新闻三我是新闻三我是新闻三我是新闻三',
    'posids' => '0',
    'url' => 'http://www.g-sky.cn/index.php?m=content&c=index&a=show&catid=13&id=4',
    'listorder' => '0',
    'status' => '99',
    'sysadd' => '1',
    'islink' => '0',
    'username' => 'admin',
    'inputtime' => '1422166753',
    'updatetime' => '1422166765',
    'hitsid' => 'c-1-4',
    'views' => '0',
    'yesterdayviews' => '0',
    'dayviews' => '0',
    'weekviews' => '0',
    'monthviews' => '0',
  ),
);
?>