<?php
return array (
  3 => 
  array (
    'id' => '3',
    'catid' => '13',
    'typeid' => '0',
    'title' => '企业新闻2',
    'style' => '',
    'thumb' => '',
    'keywords' => '企业 新闻',
    'description' => '企业新闻2企业新闻2企业新闻2企业新闻2企业新闻2企业新闻2企业新闻2企业新闻2企业新闻2企业新闻2企业新闻2企业新闻2企业新闻2企业新闻2企业   ',
    'posids' => '0',
    'url' => 'http://localhost/phpcms/index.php?m=content&c=index&a=show&catid=13&id=3',
    'listorder' => '0',
    'status' => '99',
    'sysadd' => '1',
    'islink' => '0',
    'username' => 'admin',
    'inputtime' => '1422090859',
    'updatetime' => '1422094033',
    'hitsid' => 'c-1-3',
    'views' => '2',
    'yesterdayviews' => '0',
    'dayviews' => '2',
    'weekviews' => '2',
    'monthviews' => '2',
  ),
  1 => 
  array (
    'id' => '1',
    'catid' => '13',
    'typeid' => '0',
    'title' => '我是新闻1',
    'style' => '',
    'thumb' => '',
    'keywords' => '新闻',
    'description' => '我是新闻1我是新闻1我是新闻1我是新闻1我是新闻1我是新闻1我是新闻1我是新闻1我是新闻1我是新闻1我是新闻1我是新闻1我是新闻1我是新闻1我是   ',
    'posids' => '0',
    'url' => 'http://localhost/phpcms/index.php?m=content&c=index&a=show&catid=13&id=1',
    'listorder' => '0',
    'status' => '99',
    'sysadd' => '1',
    'islink' => '0',
    'username' => 'admin',
    'inputtime' => '1422089890',
    'updatetime' => '1422090796',
    'hitsid' => 'c-1-1',
    'views' => '1',
    'yesterdayviews' => '0',
    'dayviews' => '1',
    'weekviews' => '1',
    'monthviews' => '1',
  ),
);
?>