<?php
return array (
  1 => 
  array (
    'id' => '1',
    'catid' => '13',
    'typeid' => '0',
    'title' => '我是新闻1',
    'style' => '',
    'thumb' => '',
    'keywords' => '新闻',
    'description' => '我是新闻1我是新闻1我是新闻1我是新闻1我是新闻1我是新闻1我是新闻1我是新闻1我是新闻1我是新闻1我是新闻1我是新闻1我是新闻1我是新闻1我是   ',
    'posids' => '0',
    'url' => 'http://localhost/phpcms/index.php?m=content&c=index&a=show&catid=13&id=1',
    'listorder' => '0',
    'status' => '99',
    'sysadd' => '1',
    'islink' => '0',
    'username' => 'admin',
    'inputtime' => '1422089890',
    'updatetime' => '1422090796',
    'hitsid' => 'c-1-1',
    'views' => '1',
    'yesterdayviews' => '0',
    'dayviews' => '1',
    'weekviews' => '1',
    'monthviews' => '1',
  ),
  2 => 
  array (
    'id' => '2',
    'catid' => '14',
    'typeid' => '0',
    'title' => '我是行业新闻',
    'style' => '',
    'thumb' => '',
    'keywords' => '行业 新闻',
    'description' => '我是行业新闻我是行业新闻我是行业新闻我是行业新闻我是行业新闻我是行业新闻我是行业新闻我是行业新闻我是行业新闻我是行业新闻我是行业新   ',
    'posids' => '0',
    'url' => 'http://localhost/phpcms/index.php?m=content&c=index&a=show&catid=14&id=2',
    'listorder' => '0',
    'status' => '99',
    'sysadd' => '1',
    'islink' => '0',
    'username' => 'admin',
    'inputtime' => '1422089922',
    'updatetime' => '1422093021',
    'hitsid' => 'c-1-2',
    'views' => '1',
    'yesterdayviews' => '0',
    'dayviews' => '1',
    'weekviews' => '1',
    'monthviews' => '1',
  ),
  3 => 
  array (
    'id' => '3',
    'catid' => '13',
    'typeid' => '0',
    'title' => '企业新闻2',
    'style' => '',
    'thumb' => '',
    'keywords' => '企业 新闻',
    'description' => '企业新闻2企业新闻2企业新闻2企业新闻2企业新闻2企业新闻2企业新闻2企业新闻2企业新闻2企业新闻2企业新闻2企业新闻2企业新闻2企业新闻2企业   ',
    'posids' => '0',
    'url' => 'http://localhost/phpcms/index.php?m=content&c=index&a=show&catid=13&id=3',
    'listorder' => '0',
    'status' => '99',
    'sysadd' => '1',
    'islink' => '0',
    'username' => 'admin',
    'inputtime' => '1422090859',
    'updatetime' => '1422092973',
    'hitsid' => 'c-1-3',
    'views' => '1',
    'yesterdayviews' => '0',
    'dayviews' => '1',
    'weekviews' => '1',
    'monthviews' => '1',
  ),
);
?>